### ISSUE TITLE
Not supported on ruby 2.3?

### ISSUE THREAD

**Issue by JanStevens** [jenseng/hair_trigger#50] opened 2016-01-06 07:26 UTC
Getting these warnings, and no triggers are defined.

```
Error reading triggers in db/migrate/20151029080635_create_search_index_for_personal_infos.rb: unrecognized RUBY_VERSION 2.3.0
Error reading triggers in db/migrate/20151029080635_create_search_index_for_personal_infos.rb: unrecognized RUBY_VERSION 2.3.0
Included HairTrigger::SchemaDumper in ActiveRecord::SchemaDumper
Error reading triggers in db/migrate/20151029080635_create_search_index_for_personal_infos.rb: unrecognized RUBY_VERSION 2.3.0
```

**Comment by jenseng** [comment] 2016-01-06 17:08
This is essentially the same problem as in #40 ... we rely on ruby_parser, so until it supports 2.3, we can't. As a workaround you might try something like this: https://github.com/jenseng/hair_trigger/issues/40#issuecomment-93601240

If 2.3 support doesn't come to ruby_parser anytime soon, I'll look at swapping it out for [parser](https://github.com/whitequark/parser), as it seems to stay a bit more on top of things.

**Comment by diskshima** [comment] 2016-01-27 04:43
Looks like they (ruby_parser) have added support 2.3.

https://github.com/seattlerb/ruby_parser/commit/da22d1e256305dff2bb549e9f13fcf9f69c43bb2

Any chance this may get incorporated?

**Comment by jenseng** [comment] 2016-01-27 23:27
:+1: I'll bump the dependency and cut a new release. That said, you should be able to get it to work on the current version of hairtrigger if you explicitly add the latest ruby_parser to your Gemfile

**Comment by diskshima** [comment] 2016-01-27 23:30
Ah that's true. Thanks for the quick turnaround and your advice about Gemfile.

**Comment by cavneb** [comment] 2016-07-14 16:59
This still appears to be an issue with JRuby 9.1.2.0 (2.3.0)

**Comment by jenseng** [comment] 2016-07-14 17:04
Whoopsie, I forgot to bump the dependency and ship a new version 😮  ... in the meantime, @cavneb have you tried the workaround suggested above? Perhaps you just need to be explicit about using the latest ruby_parser?

**Comment by jvrsgsty** [comment] 2016-08-30 15:45
Having some issues getting this gem up and running in Rails 5.0.0.1 and Ruby 2.3.1 with a Postgres DB. I was able to install the gem, but the rake task to generate the migrations fails with a couple of Deprecation Warnings and an error. Has anyone tried this out on Rails 5?

I see the latest commit hasn't been merged into master and the gem has not been updated on [rubygems.org](https://rubygems.org/gems/hairtrigger/versions/0.2.17) since December. Perhaps you haven't shipped the newest version @jenseng?

**Comment by memoht** [comment] 2016-12-01 04:31
I can confirm running into issues trying to use this gem on `Rais 5.0.0.1` and `Ruby 2.3.3` with Postgres 9.5 database. I ended up with something like this ```DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /Users/memoht/Sites/ppipub/config/application.rb:19)
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /Users/memoht/Sites/ppipub/config/application.rb:19)```

@jvrsgsty In order to make progress I ended up following this article and seem to have luck. https://robots.thoughtbot.com/optimizing-full-text-search-with-postgres-tsvector-columns-and-triggers

+1 for updating this gem.

**Closed** 2017-02-04 06:43 UTC
